enum APIRoute {
    // Auth routes
    LOGIN = 'auth/login',
    LOGOUT = 'auth/logout',
    FORGOT_PASS = 'auth/password/forgot',
    RESET_PASS = 'auth/password/reset',
    RESEND_CONF_EMAIL = 'auth/confirm/resend',
    CHANGE_PASS = 'auth/password/change',
    // Account routes
    ACCOUNT = 'account',
    ACCOUNT_SELF = 'account/self',
    ACCOUNT_INVITE = 'account/invite',
    // Hacker routes
    HACKER = 'hacker',
    HACKER_SELF = 'hacker/self',
    HACKER_RESUME = 'hacker/resume',
    HACKER_STATUS = 'hacker/status',
    HACKER_CHECKIN = 'hacker/checkin',
    // Search routes
    SEARCH = 'search',
    // Sponsor routes
    SPONSOR = 'sponsor',
};
export default APIRoute;