export const API_URL = 'http://localhost:3000/api';

// Application creation
export const BUS_REQUEST_LABEL = 'Do you need a bus?';
export const BUS_REQUEST_SUBTITLE = 'We will be sending busses to Toronto, Waterloo, London, Ottowa, Kingston, and Boston.'
export const COC_REQUEST_LABEL = 'I accept the MLH terms, conditions and guidlelines';
export const COMMENTS_REQUEST_LABEL = 'Anything else you would like us to know?';
export const DROPLER_LINK_LABEL = 'Droplr Username';
export const DROPLER_LINK_PLACEHOLDER = 'https://droplr.com/';
export const ESSAY_REQUEST_LABEL = 'Why McHacks?';
export const ETHNICITY_REQUEST_LABEL = 'What is your ethnicity?';
export const ETHNICITY_REQUEST_PLACEHOLDER = 'Ethnicity...';
export const GENDER_REQUEST_LABEL = 'What gender do you identify with?';
export const GENDER_REQUEST_PLACEHOLDER = 'Gender...';
export const GITHUB_LINK_LABEL = 'GitHub Username';
export const GITHUB_LINK_PLACEHOLDER = 'https://www.github.com/';
export const JOBINTEREST_REQUEST_LABEL = 'Are you looking for a job?';
export const JOBINTEREST_REQUEST_PLACEHOLDER = 'Job interests...';
export const LINKEDIN_LINK_LABEL = 'linkedIn';
export const LINKEDIN_LINK_PLACEHOLDER = 'http://linkedin.com/in/';
export const MAJOR_PLACEHOLDER = 'major...';
export const MAJOR_REQUEST_LABEL = 'What is (are) your field(s) of study?';
export const OTHER_LINK_LABEL = 'other links you want us to know';
export const OTHER_LINK_PLACEHOLDER = 'anything else!';
export const PERSONAL_LINK_LABEL = 'Personal';
export const PERSONAL_LINK_PLACEHOLDER = 'your website here...';
export const RESUME_REQUEST_LABEL = 'Upload a resume';
export const SKILLS_REQUEST_LABEL = 'What skills do you have?';
export const SKILLS_REQUEST_PLACEHOLDER = 'Javascript, iOS, Android...';