const MajorsList = [
  'Accounting',
  'Actuarial Science',
  'Anthropology',
  'Architecture',
  'Biochemistry',
  'Bioengineering',
  'Biology',
  'Chemical Engineering',
  'Chemistry',
  'Civil Engineering',
  'Communications',
  'Computer Engineering',
  'Computer Science',
  'Criminology',
  'Dentistry',
  'Earth Sciences',
  'East Asian Studies',
  'Economics',
  'Education',
  'Electrical Engineering',
  'English',
  'Environment',
  'Environmental Engineering',
  'Film',
  'Finance',
  'Fine Arts',
  'Geography',
  'Gender Studies',
  'History',
  'Industrial Relations',
  'Information Systems',
  'International Development',
  'Journalism',
  'Kinesiology',
  'Law',
  'Liberal Arts',
  'Life Sciences',
  'Linguistics',
  'Literature',
  'Management',
  'Materials Engineering',
  'Mathematics',
  'Marketing',
  'Mechanical Engineering',
  'Mechatronics Engineering',
  'Medicine',
  'Mining Engineering',
  'Music',
  'Nanotechnology Engineering',
  'Neuroscience',
  'Nursing',
  'Nutrition',
  'Pharmacology',
  'Philosophy',
  'Physics',
  'Physiology',
  'Political Science',
  'Psychology',
  'Religious Studies',
  'Sociology',
  'Software Engineering',
  'Systems Design Engineering',
  'Statistics',
  'Theatre',
];

export const Majors = MajorsList.map((v) => ({ label: v, value: v }));
export default Majors;
