const MajorsList = [
  'Accounting',
  'Actuarial Science',
  'Anthropology',
  'Architecture',
  'Biochemistry',
  'Bioengineering',
  'Biology',
  'Biotechnology',
  'Business',
  'Business Analytics',
  'Chemical Engineering',
  'Chemistry',
  'Civil Engineering',
  'Communications',
  'Computer Engineering',
  'Computer Science',
  'Criminology',
  'Cultural Studies',
  'Data Science',
  'Dentistry',
  'Earth Sciences',
  'East Asian Studies',
  'Economics',
  'Education',
  'Electrical Engineering',
  'Engineering',
  'Engineering Chemistry',
  'Engineering Physics',
  'English',
  'Entrepreneurship',
  'Environment',
  'Environmental Engineering',
  'Film',
  'Finance',
  'Fine Arts',
  'Geography',
  'Geological Engineering',
  'Gender Studies',
  'History',
  'Industrial Relations',
  'Information Systems',
  'International Development',
  'Journalism',
  'Kinesiology',
  'Law',
  'Liberal Arts',
  'Life Sciences',
  'Linguistics',
  'Literature',
  'Management',
  'Materials Engineering',
  'Mathematics',
  'Marketing',
  'Mechanical Engineering',
  'Mechatronics Engineering',
  'Medicine',
  'Mineral Engineering',
  'Mining Engineering',
  'Music',
  'Nanotechnology Engineering',
  'Neuroscience',
  'Nursing',
  'Nutrition',
  'Information Systems',
  'Pharmacology',
  'Philosophy',
  'Physics',
  'Physiology',
  'Political Science',
  'Psychology',
  'Religious Studies',
  'Retail Management',
  'Sociology',
  'Software Engineering',
  'Sustainability',
  'Systems Design Engineering',
  'Statistics',
  'Theatre',
];

export const Majors = MajorsList.map((v) => ({ label: v, value: v }));
export default Majors;
