enum Route {
    // Auth routes
    LOGIN = 'auth/login',
    LOGOUT = 'auth/logout',
    FORGOT_PASS = 'auth/password/forgot',
    RESET_PASS = 'auth/password/reset',
    // Account routes
    ACCOUNT = 'account',
    ACCOUNT_SELF = 'account/self',
    ACCOUNT_INVITE = 'account/invite',
    // Hacker routes
    HACKER = 'hacker',
    HACKER_SELF = 'hacker/self',
    HACKER_RESUME = 'hacker/resume',
    // Search routes
    SEARCH = 'search',
    // Sponsor routes
    SPONSOR = 'sponsor',
};
export default Route;