export enum Skills {
    Android = 'Android',
    ArtificialIntelligence = 'Artificial Intelligence',
    BackEnd = 'Back-End',
    C = 'C',
    CSharp = 'C#',
    CPlusPlus = 'C++',
    CSS = 'CSS',
    DataScience = 'Data Science',
    DesktopApps = 'Desktop Apps',
    Django = 'Django',
    Excel = 'Excel',
    FrontEnd = 'Front-End',
    HTML = 'HTML',
    iOS = 'iOS',
    Java = 'Java',
    Javascript = 'Javascript',
    JS = 'JS',
    MachineLearning = 'Machine Learning',
    MobileApps = 'Mobile Apps',
    MongoDB = 'MongoDB',
    NaturalLanguageProcessing = 'Natural Language Processing',
    NodeJS = 'Node.JS',
    PHP = 'PHP',
    ProductManagement = 'Product Management',
    Python = 'Python',
    React = 'React',
    Robotics = 'Robotics',
    Ruby = 'Ruby',
    RubyonRails = 'Ruby on Rails',
    Swift = 'Swift',
    Typescript = 'Typescript',
    TS = 'TS',
    UIDesign = 'UI Design',
    UXDesign = 'UX Design',
}
export default Skills;

